//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Endoresement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BASEOBJECT", Namespace="http://schemas.datacontract.org/2004/07/MedicalComponent.DOL.CommonObjects")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Endoresement.POLICIES_DOL))]
    public partial class BASEOBJECT : object
    {
        
        private string CreatedByField;
        
        private System.DateTime CreationDateField;
        
        private System.DateTime ModificationDateField;
        
        private string ModifiedByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModificationDate
        {
            get
            {
                return this.ModificationDateField;
            }
            set
            {
                this.ModificationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POLICIES_DOL", Namespace="http://schemas.datacontract.org/2004/07/MedicalComponent.DOL.Production")]
    public partial class POLICIES_DOL : Endoresement.BASEOBJECT
    {
        
        private int APPROVAL_STATUSField;
        
        private string BranchNameField;
        
        private string CRM_LEAD_NAMEField;
        
        private System.Nullable<long> CRM_LED_IDField;
        
        private System.Nullable<int> E_FORMS_CLASS_TYPEField;
        
        private string EndorsementNameField;
        
        private int IS_CONVERTEDField;
        
        private System.Nullable<int> POLICY_HOLDER_TYPEField;
        
        private string PaymentNameField;
        
        private string PlanNameField;
        
        private System.Nullable<int> QuotationStatusNameField;
        
        private int DocumentTypeField;
        
        private decimal PolicyNoField;
        
        private int PolicyTypeField;
        
        private int RenewalNoField;
        
        private int EndorsementNoField;
        
        private int UWYearField;
        
        private string ReferenceNoField;
        
        private System.Nullable<System.DateTime> ReferenceDateField;
        
        private System.DateTime IssueDateField;
        
        private System.DateTime EffectiveDateField;
        
        private System.DateTime ExpiryDateField;
        
        private int BusinessTypeField;
        
        private int CalculationTypeField;
        
        private System.Nullable<int> FamilyClassFlagField;
        
        private System.Nullable<decimal> ExtraNRPField;
        
        private System.Nullable<decimal> LoadingField;
        
        private System.Nullable<decimal> DiscountField;
        
        private string NotesField;
        
        private decimal ExrateField;
        
        private long PaymentIDField;
        
        private long EndorsementIDField;
        
        private long PlanIDField;
        
        private System.Nullable<long> OriginalPolicyIDField;
        
        private System.Nullable<long> RenewedPolicyIDField;
        
        private System.Nullable<long> QuotationIDField;
        
        private System.Nullable<long> PolicyHolderIDField;
        
        private string CurrencyCodeField;
        
        private System.Nullable<int> CompanyIDField;
        
        private System.Nullable<int> BranchIDField;
        
        private long TpaTypeField;
        
        private System.Nullable<System.DateTime> ReceviedDateField;
        
        private System.Nullable<long> SalesCollectorField;
        
        private int AccountedForField;
        
        private System.Nullable<long> AccountIDField;
        
        private System.Nullable<long> AccountedToField;
        
        private System.Nullable<int> QuotationTypeField;
        
        private int APPLICANT_TYPEField;
        
        private string APPLICANT_NAMEField;
        
        private int DURATIONField;
        
        private int DURATION_UNITField;
        
        private long PolicyIDField;
        
        private System.Nullable<int> TERMINATION_REASONField;
        
        private string TERMINATION_DETAILSField;
        
        private string SegmentCodeField;
        
        private System.Nullable<long> BusinessChannelField;
        
        private System.Nullable<long> MPD_APP_IDField;
        
        private decimal NetPremiumField;
        
        private decimal NetPremiumLCField;
        
        private decimal GrossPremiumField;
        
        private decimal GrossPremiumLCField;
        
        private decimal TotalPremiumField;
        
        private decimal TotalPremiumLCField;
        
        private System.Nullable<long> ProductIDField;
        
        private string PROMOTION_CODEField;
        
        private System.Nullable<long> CONVERT_POLICY_IDField;
        
        private int IS_POSTEDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int APPROVAL_STATUS
        {
            get
            {
                return this.APPROVAL_STATUSField;
            }
            set
            {
                this.APPROVAL_STATUSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRM_LEAD_NAME
        {
            get
            {
                return this.CRM_LEAD_NAMEField;
            }
            set
            {
                this.CRM_LEAD_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CRM_LED_ID
        {
            get
            {
                return this.CRM_LED_IDField;
            }
            set
            {
                this.CRM_LED_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> E_FORMS_CLASS_TYPE
        {
            get
            {
                return this.E_FORMS_CLASS_TYPEField;
            }
            set
            {
                this.E_FORMS_CLASS_TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndorsementName
        {
            get
            {
                return this.EndorsementNameField;
            }
            set
            {
                this.EndorsementNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IS_CONVERTED
        {
            get
            {
                return this.IS_CONVERTEDField;
            }
            set
            {
                this.IS_CONVERTEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> POLICY_HOLDER_TYPE
        {
            get
            {
                return this.POLICY_HOLDER_TYPEField;
            }
            set
            {
                this.POLICY_HOLDER_TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentName
        {
            get
            {
                return this.PaymentNameField;
            }
            set
            {
                this.PaymentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanName
        {
            get
            {
                return this.PlanNameField;
            }
            set
            {
                this.PlanNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuotationStatusName
        {
            get
            {
                return this.QuotationStatusNameField;
            }
            set
            {
                this.QuotationStatusNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public decimal PolicyNo
        {
            get
            {
                return this.PolicyNoField;
            }
            set
            {
                this.PolicyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int PolicyType
        {
            get
            {
                return this.PolicyTypeField;
            }
            set
            {
                this.PolicyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int RenewalNo
        {
            get
            {
                return this.RenewalNoField;
            }
            set
            {
                this.RenewalNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int EndorsementNo
        {
            get
            {
                return this.EndorsementNoField;
            }
            set
            {
                this.EndorsementNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int UWYear
        {
            get
            {
                return this.UWYearField;
            }
            set
            {
                this.UWYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string ReferenceNo
        {
            get
            {
                return this.ReferenceNoField;
            }
            set
            {
                this.ReferenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<System.DateTime> ReferenceDate
        {
            get
            {
                return this.ReferenceDateField;
            }
            set
            {
                this.ReferenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.DateTime IssueDate
        {
            get
            {
                return this.IssueDateField;
            }
            set
            {
                this.IssueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int BusinessType
        {
            get
            {
                return this.BusinessTypeField;
            }
            set
            {
                this.BusinessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int CalculationType
        {
            get
            {
                return this.CalculationTypeField;
            }
            set
            {
                this.CalculationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<int> FamilyClassFlag
        {
            get
            {
                return this.FamilyClassFlagField;
            }
            set
            {
                this.FamilyClassFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtraNRP%", Order=25)]
        public System.Nullable<decimal> ExtraNRP
        {
            get
            {
                return this.ExtraNRPField;
            }
            set
            {
                this.ExtraNRPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Loading%", Order=26)]
        public System.Nullable<decimal> Loading
        {
            get
            {
                return this.LoadingField;
            }
            set
            {
                this.LoadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Discount%", Order=27)]
        public System.Nullable<decimal> Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public decimal Exrate
        {
            get
            {
                return this.ExrateField;
            }
            set
            {
                this.ExrateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public long PaymentID
        {
            get
            {
                return this.PaymentIDField;
            }
            set
            {
                this.PaymentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public long EndorsementID
        {
            get
            {
                return this.EndorsementIDField;
            }
            set
            {
                this.EndorsementIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public long PlanID
        {
            get
            {
                return this.PlanIDField;
            }
            set
            {
                this.PlanIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public System.Nullable<long> OriginalPolicyID
        {
            get
            {
                return this.OriginalPolicyIDField;
            }
            set
            {
                this.OriginalPolicyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public System.Nullable<long> RenewedPolicyID
        {
            get
            {
                return this.RenewedPolicyIDField;
            }
            set
            {
                this.RenewedPolicyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public System.Nullable<long> QuotationID
        {
            get
            {
                return this.QuotationIDField;
            }
            set
            {
                this.QuotationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public System.Nullable<long> PolicyHolderID
        {
            get
            {
                return this.PolicyHolderIDField;
            }
            set
            {
                this.PolicyHolderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public System.Nullable<int> CompanyID
        {
            get
            {
                return this.CompanyIDField;
            }
            set
            {
                this.CompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public System.Nullable<int> BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public long TpaType
        {
            get
            {
                return this.TpaTypeField;
            }
            set
            {
                this.TpaTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public System.Nullable<System.DateTime> ReceviedDate
        {
            get
            {
                return this.ReceviedDateField;
            }
            set
            {
                this.ReceviedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public System.Nullable<long> SalesCollector
        {
            get
            {
                return this.SalesCollectorField;
            }
            set
            {
                this.SalesCollectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public int AccountedFor
        {
            get
            {
                return this.AccountedForField;
            }
            set
            {
                this.AccountedForField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public System.Nullable<long> AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public System.Nullable<long> AccountedTo
        {
            get
            {
                return this.AccountedToField;
            }
            set
            {
                this.AccountedToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public System.Nullable<int> QuotationType
        {
            get
            {
                return this.QuotationTypeField;
            }
            set
            {
                this.QuotationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public int APPLICANT_TYPE
        {
            get
            {
                return this.APPLICANT_TYPEField;
            }
            set
            {
                this.APPLICANT_TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public string APPLICANT_NAME
        {
            get
            {
                return this.APPLICANT_NAMEField;
            }
            set
            {
                this.APPLICANT_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public int DURATION
        {
            get
            {
                return this.DURATIONField;
            }
            set
            {
                this.DURATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public int DURATION_UNIT
        {
            get
            {
                return this.DURATION_UNITField;
            }
            set
            {
                this.DURATION_UNITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=51)]
        public long PolicyID
        {
            get
            {
                return this.PolicyIDField;
            }
            set
            {
                this.PolicyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=52)]
        public System.Nullable<int> TERMINATION_REASON
        {
            get
            {
                return this.TERMINATION_REASONField;
            }
            set
            {
                this.TERMINATION_REASONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=53)]
        public string TERMINATION_DETAILS
        {
            get
            {
                return this.TERMINATION_DETAILSField;
            }
            set
            {
                this.TERMINATION_DETAILSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=54)]
        public string SegmentCode
        {
            get
            {
                return this.SegmentCodeField;
            }
            set
            {
                this.SegmentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=55)]
        public System.Nullable<long> BusinessChannel
        {
            get
            {
                return this.BusinessChannelField;
            }
            set
            {
                this.BusinessChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=56)]
        public System.Nullable<long> MPD_APP_ID
        {
            get
            {
                return this.MPD_APP_IDField;
            }
            set
            {
                this.MPD_APP_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=57)]
        public decimal NetPremium
        {
            get
            {
                return this.NetPremiumField;
            }
            set
            {
                this.NetPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=58)]
        public decimal NetPremiumLC
        {
            get
            {
                return this.NetPremiumLCField;
            }
            set
            {
                this.NetPremiumLCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=59)]
        public decimal GrossPremium
        {
            get
            {
                return this.GrossPremiumField;
            }
            set
            {
                this.GrossPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=60)]
        public decimal GrossPremiumLC
        {
            get
            {
                return this.GrossPremiumLCField;
            }
            set
            {
                this.GrossPremiumLCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=61)]
        public decimal TotalPremium
        {
            get
            {
                return this.TotalPremiumField;
            }
            set
            {
                this.TotalPremiumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=62)]
        public decimal TotalPremiumLC
        {
            get
            {
                return this.TotalPremiumLCField;
            }
            set
            {
                this.TotalPremiumLCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=63)]
        public System.Nullable<long> ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=64)]
        public string PROMOTION_CODE
        {
            get
            {
                return this.PROMOTION_CODEField;
            }
            set
            {
                this.PROMOTION_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=65)]
        public System.Nullable<long> CONVERT_POLICY_ID
        {
            get
            {
                return this.CONVERT_POLICY_IDField;
            }
            set
            {
                this.CONVERT_POLICY_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=66)]
        public int IS_POSTED
        {
            get
            {
                return this.IS_POSTEDField;
            }
            set
            {
                this.IS_POSTEDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndorsementOutput", Namespace="http://schemas.datacontract.org/2004/07/MedicalWCF.Interface")]
    public partial class EndorsementOutput : object
    {
        
        private Endoresement.StatusCT StatusField;
        
        private Endoresement.POLICIES_DOL oPolicyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Endoresement.StatusCT Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Endoresement.POLICIES_DOL oPolicy
        {
            get
            {
                return this.oPolicyField;
            }
            set
            {
                this.oPolicyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCT", Namespace="http://schemas.datacontract.org/2004/07/MedicalWCF.Interface")]
    public partial class StatusCT : object
    {
        
        private string _ReasonField;
        
        private System.DateTime _ReasonDateField;
        
        private int _StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Reason
        {
            get
            {
                return this._ReasonField;
            }
            set
            {
                this._ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _ReasonDate
        {
            get
            {
                return this._ReasonDateField;
            }
            set
            {
                this._ReasonDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _StatusCode
        {
            get
            {
                return this._StatusCodeField;
            }
            set
            {
                this._StatusCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Endoresement.IENDORSEMENT")]
    public interface IENDORSEMENT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENDORSEMENT/EndorsementInsert", ReplyAction="http://tempuri.org/IENDORSEMENT/EndorsementInsertResponse")]
        Endoresement.EndorsementOutput EndorsementInsert(int PolicyID, Endoresement.POLICIES_DOL oPOLICIES_INPUT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENDORSEMENT/EndorsementInsert", ReplyAction="http://tempuri.org/IENDORSEMENT/EndorsementInsertResponse")]
        System.Threading.Tasks.Task<Endoresement.EndorsementOutput> EndorsementInsertAsync(int PolicyID, Endoresement.POLICIES_DOL oPOLICIES_INPUT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENDORSEMENT/EndorsementUpdate", ReplyAction="http://tempuri.org/IENDORSEMENT/EndorsementUpdateResponse")]
        Endoresement.EndorsementOutput EndorsementUpdate(Endoresement.POLICIES_DOL oPOLICIES_INPUT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IENDORSEMENT/EndorsementUpdate", ReplyAction="http://tempuri.org/IENDORSEMENT/EndorsementUpdateResponse")]
        System.Threading.Tasks.Task<Endoresement.EndorsementOutput> EndorsementUpdateAsync(Endoresement.POLICIES_DOL oPOLICIES_INPUT);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IENDORSEMENTChannel : Endoresement.IENDORSEMENT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ENDORSEMENTClient : System.ServiceModel.ClientBase<Endoresement.IENDORSEMENT>, Endoresement.IENDORSEMENT
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ENDORSEMENTClient(EndpointConfiguration endpointConfiguration) : 
                base(ENDORSEMENTClient.GetBindingForEndpoint(endpointConfiguration), ENDORSEMENTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENDORSEMENTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ENDORSEMENTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENDORSEMENTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ENDORSEMENTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ENDORSEMENTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Endoresement.EndorsementOutput EndorsementInsert(int PolicyID, Endoresement.POLICIES_DOL oPOLICIES_INPUT)
        {
            return base.Channel.EndorsementInsert(PolicyID, oPOLICIES_INPUT);
        }
        
        public System.Threading.Tasks.Task<Endoresement.EndorsementOutput> EndorsementInsertAsync(int PolicyID, Endoresement.POLICIES_DOL oPOLICIES_INPUT)
        {
            return base.Channel.EndorsementInsertAsync(PolicyID, oPOLICIES_INPUT);
        }
        
        public Endoresement.EndorsementOutput EndorsementUpdate(Endoresement.POLICIES_DOL oPOLICIES_INPUT)
        {
            return base.Channel.EndorsementUpdate(oPOLICIES_INPUT);
        }
        
        public System.Threading.Tasks.Task<Endoresement.EndorsementOutput> EndorsementUpdateAsync(Endoresement.POLICIES_DOL oPOLICIES_INPUT)
        {
            return base.Channel.EndorsementUpdateAsync(oPOLICIES_INPUT);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IENDORSEMENT))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IENDORSEMENT))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IENDORSEMENT))
            {
                return new System.ServiceModel.EndpointAddress("http://10.150.8.154/MIService/MedicalWCF.ServiceMethod.ENDORSEMENT.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IENDORSEMENT))
            {
                return new System.ServiceModel.EndpointAddress("https://eskauatnew.sstc.local/MIService/MedicalWCF.ServiceMethod.ENDORSEMENT.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IENDORSEMENT,
            
            BasicHttpsBinding_IENDORSEMENT,
        }
    }
}
