//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EskaReports
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadReportInput", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class LoadReportInput : object
    {
        
        private string CodeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadReportOutput", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class LoadReportOutput : object
    {
        
        private EskaReports.Report oReportField;
        
        private EskaReports.Status oStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.Report oReport
        {
            get
            {
                return this.oReportField;
            }
            set
            {
                this.oReportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.Status oStatus
        {
            get
            {
                return this.oStatusField;
            }
            set
            {
                this.oStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class Report : object
    {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private string Name2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name2
        {
            get
            {
                return this.Name2Field;
            }
            set
            {
                this.Name2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class Status : object
    {
        
        private string ReasonField;
        
        private System.DateTime ReasonDateField;
        
        private int StatusCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReasonDate
        {
            get
            {
                return this.ReasonDateField;
            }
            set
            {
                this.ReasonDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadReportParametersInput", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class LoadReportParametersInput : object
    {
        
        private string ReportCodeField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCode
        {
            get
            {
                return this.ReportCodeField;
            }
            set
            {
                this.ReportCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadReportParametersOutput", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class LoadReportParametersOutput : object
    {
        
        private EskaReports.ReportParameter[] oReportParametersField;
        
        private EskaReports.Status oStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.ReportParameter[] oReportParameters
        {
            get
            {
                return this.oReportParametersField;
            }
            set
            {
                this.oReportParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.Status oStatus
        {
            get
            {
                return this.oStatusField;
            }
            set
            {
                this.oStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportParameter", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class ReportParameter : object
    {
        
        private EskaReports.UtilitiesBLLParameterType ColumnTypeField;
        
        private string FromValueField;
        
        private string ParamFromField;
        
        private string ParamFromDescriptionField;
        
        private bool ParamFromRequiredField;
        
        private int ParamIDField;
        
        private int ParamOrderField;
        
        private string ParamToField;
        
        private string ParamToDescriptionField;
        
        private bool ParamToRequiredField;
        
        private string ReportCodeField;
        
        private string ToValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.UtilitiesBLLParameterType ColumnType
        {
            get
            {
                return this.ColumnTypeField;
            }
            set
            {
                this.ColumnTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromValue
        {
            get
            {
                return this.FromValueField;
            }
            set
            {
                this.FromValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamFrom
        {
            get
            {
                return this.ParamFromField;
            }
            set
            {
                this.ParamFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamFromDescription
        {
            get
            {
                return this.ParamFromDescriptionField;
            }
            set
            {
                this.ParamFromDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ParamFromRequired
        {
            get
            {
                return this.ParamFromRequiredField;
            }
            set
            {
                this.ParamFromRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParamID
        {
            get
            {
                return this.ParamIDField;
            }
            set
            {
                this.ParamIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParamOrder
        {
            get
            {
                return this.ParamOrderField;
            }
            set
            {
                this.ParamOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamTo
        {
            get
            {
                return this.ParamToField;
            }
            set
            {
                this.ParamToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParamToDescription
        {
            get
            {
                return this.ParamToDescriptionField;
            }
            set
            {
                this.ParamToDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ParamToRequired
        {
            get
            {
                return this.ParamToRequiredField;
            }
            set
            {
                this.ParamToRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCode
        {
            get
            {
                return this.ReportCodeField;
            }
            set
            {
                this.ReportCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToValue
        {
            get
            {
                return this.ToValueField;
            }
            set
            {
                this.ToValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilitiesBLL.ParameterType", Namespace="http://schemas.datacontract.org/2004/07/CoreEssentials.BLL")]
    public enum UtilitiesBLLParameterType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Number = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Character = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOV = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DLOV = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultiList = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateReportInput", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class GenerateReportInput : object
    {
        
        private EskaReports.ApplicationsEnum ApplicationIDField;
        
        private string FileNameField;
        
        private EskaReports.LangugesEnum LangauageField;
        
        private EskaReports.ReportExportTypesEnum OutputTypeField;
        
        private string PathField;
        
        private string ReportCodeField;
        
        private string UserNameField;
        
        private EskaReports.ReportParameter[] oReportParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.ApplicationsEnum ApplicationID
        {
            get
            {
                return this.ApplicationIDField;
            }
            set
            {
                this.ApplicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.LangugesEnum Langauage
        {
            get
            {
                return this.LangauageField;
            }
            set
            {
                this.LangauageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.ReportExportTypesEnum OutputType
        {
            get
            {
                return this.OutputTypeField;
            }
            set
            {
                this.OutputTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportCode
        {
            get
            {
                return this.ReportCodeField;
            }
            set
            {
                this.ReportCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.ReportParameter[] oReportParameters
        {
            get
            {
                return this.oReportParametersField;
            }
            set
            {
                this.oReportParametersField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationsEnum", Namespace="http://schemas.datacontract.org/2004/07/ESKADENIA.Framework.Common")]
    public enum ApplicationsEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fleet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralInsurance = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MedicalInsurance = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RuleEngine = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifeInsurance = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TravelInsurance = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        iCore3 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERP = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportManager = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HR_Payroll = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GlobalLanding = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovalProcess = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRM = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eInsurance = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERP_Internet = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF = 193,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMS = 194,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Financial = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bancassurance = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CareNet = 203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifeBancassurance = 204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IslamicInsurance = 206,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectManagement = 220,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Production = 221,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manufacturing = 222,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRServices = 250,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IMS = 252,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PM = 253,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServicesBilling = 254,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportsBuilder = 255,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sales = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        POS = 257,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LawFirm = 258,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuditTrail = 300,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrokerageSystem = 301,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Communication = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Logging = 260,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LicenseManagement = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataStoryBoard = 303,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BCRM = 304,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EskaCloud = 305,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotificationScheduler = 306,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Academy = 307,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRPortalAPP = 308,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loans = 309,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LangugesEnum", Namespace="http://schemas.datacontract.org/2004/07/ESKADENIA.Framework.Common")]
    public enum LangugesEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arabic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        French = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportExportTypesEnum", Namespace="http://schemas.datacontract.org/2004/07/ESKADENIA.Framework.Common")]
    public enum ReportExportTypesEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excel = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Word = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExcelRecords = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RichText = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateReportOutput", Namespace="http://schemas.datacontract.org/2004/07/CoreInterfaces.Interfaces")]
    public partial class GenerateReportOutput : object
    {
        
        private string GeneratedReportPathField;
        
        private EskaReports.Report oReportField;
        
        private EskaReports.Status oStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneratedReportPath
        {
            get
            {
                return this.GeneratedReportPathField;
            }
            set
            {
                this.GeneratedReportPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.Report oReport
        {
            get
            {
                return this.oReportField;
            }
            set
            {
                this.oReportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EskaReports.Status oStatus
        {
            get
            {
                return this.oStatusField;
            }
            set
            {
                this.oStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EskaReports.IREPORT")]
    public interface IREPORT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREPORT/LoadReport", ReplyAction="http://tempuri.org/IREPORT/LoadReportResponse")]
        EskaReports.LoadReportResponse LoadReport(EskaReports.LoadReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREPORT/LoadReport", ReplyAction="http://tempuri.org/IREPORT/LoadReportResponse")]
        System.Threading.Tasks.Task<EskaReports.LoadReportResponse> LoadReportAsync(EskaReports.LoadReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREPORT/LoadReportParameters", ReplyAction="http://tempuri.org/IREPORT/LoadReportParametersResponse")]
        EskaReports.LoadReportParametersResponse LoadReportParameters(EskaReports.LoadReportParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREPORT/LoadReportParameters", ReplyAction="http://tempuri.org/IREPORT/LoadReportParametersResponse")]
        System.Threading.Tasks.Task<EskaReports.LoadReportParametersResponse> LoadReportParametersAsync(EskaReports.LoadReportParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREPORT/GenerateReport", ReplyAction="http://tempuri.org/IREPORT/GenerateReportResponse")]
        EskaReports.GenerateReportResponse GenerateReport(EskaReports.GenerateReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IREPORT/GenerateReport", ReplyAction="http://tempuri.org/IREPORT/GenerateReportResponse")]
        System.Threading.Tasks.Task<EskaReports.GenerateReportResponse> GenerateReportAsync(EskaReports.GenerateReportRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EskaReports.LoadReportInput oLoadReportInput;
        
        public LoadReportRequest()
        {
        }
        
        public LoadReportRequest(EskaReports.LoadReportInput oLoadReportInput)
        {
            this.oLoadReportInput = oLoadReportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EskaReports.LoadReportOutput LoadReportResult;
        
        public LoadReportResponse()
        {
        }
        
        public LoadReportResponse(EskaReports.LoadReportOutput LoadReportResult)
        {
            this.LoadReportResult = LoadReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadReportParameters", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadReportParametersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EskaReports.LoadReportParametersInput oLoadReportParametersInput;
        
        public LoadReportParametersRequest()
        {
        }
        
        public LoadReportParametersRequest(EskaReports.LoadReportParametersInput oLoadReportParametersInput)
        {
            this.oLoadReportParametersInput = oLoadReportParametersInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadReportParametersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadReportParametersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EskaReports.LoadReportParametersOutput LoadReportParametersResult;
        
        public LoadReportParametersResponse()
        {
        }
        
        public LoadReportParametersResponse(EskaReports.LoadReportParametersOutput LoadReportParametersResult)
        {
            this.LoadReportParametersResult = LoadReportParametersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerateReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EskaReports.GenerateReportInput oGenerateReportInput;
        
        public GenerateReportRequest()
        {
        }
        
        public GenerateReportRequest(EskaReports.GenerateReportInput oGenerateReportInput)
        {
            this.oGenerateReportInput = oGenerateReportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerateReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EskaReports.GenerateReportOutput GenerateReportResult;
        
        public GenerateReportResponse()
        {
        }
        
        public GenerateReportResponse(EskaReports.GenerateReportOutput GenerateReportResult)
        {
            this.GenerateReportResult = GenerateReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IREPORTChannel : EskaReports.IREPORT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class REPORTClient : System.ServiceModel.ClientBase<EskaReports.IREPORT>, EskaReports.IREPORT
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public REPORTClient() : 
                base(REPORTClient.GetDefaultBinding(), REPORTClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IREPORT.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public REPORTClient(EndpointConfiguration endpointConfiguration) : 
                base(REPORTClient.GetBindingForEndpoint(endpointConfiguration), REPORTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public REPORTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(REPORTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public REPORTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(REPORTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public REPORTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public EskaReports.LoadReportResponse LoadReport(EskaReports.LoadReportRequest request)
        {
            return base.Channel.LoadReport(request);
        }
        
        public System.Threading.Tasks.Task<EskaReports.LoadReportResponse> LoadReportAsync(EskaReports.LoadReportRequest request)
        {
            return base.Channel.LoadReportAsync(request);
        }
        
        public EskaReports.LoadReportParametersResponse LoadReportParameters(EskaReports.LoadReportParametersRequest request)
        {
            return base.Channel.LoadReportParameters(request);
        }
        
        public System.Threading.Tasks.Task<EskaReports.LoadReportParametersResponse> LoadReportParametersAsync(EskaReports.LoadReportParametersRequest request)
        {
            return base.Channel.LoadReportParametersAsync(request);
        }
        
        public EskaReports.GenerateReportResponse GenerateReport(EskaReports.GenerateReportRequest request)
        {
            return base.Channel.GenerateReport(request);
        }
        
        public System.Threading.Tasks.Task<EskaReports.GenerateReportResponse> GenerateReportAsync(EskaReports.GenerateReportRequest request)
        {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IREPORT))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IREPORT))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://eskauatnew.sstc.local/CoreInterface/CoreInterfaces.Services.REPORT.svc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return REPORTClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IREPORT);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return REPORTClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IREPORT);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IREPORT,
        }
    }
}
