using System;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using Domain.Common;
using Domain.Models.CustomModels;
using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.Exchange.WebServices.Data;
using Microsoft.Extensions.Logging;
using MimeKit;
using Service.Interfaces;

namespace Service.Services
{
	public class EwsService : IEwsService
	{
		private readonly EmailConfiguration _emailConfiguration;

		private string Templete = "<html>\r\n<head>\r\n    <title>Error Notification Email</title>\r\n    <style type=\"text/css\">\r\n        body\r\n        {\r\n            font-family: Tahoma;\r\n            font-size: 14px;\r\n        }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div>\r\n        Dear sir,<br />\r\n        Please note that the following error has occured:\r\n    </div>\r\n    <br />\r\n    <div>\r\n        <table cellpadding=\"0\" cellspacing=\"6\" border=\"0\">\r\n            <tr>\r\n                <td>\r\n                    <b>Error Details : </b>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td>\r\n                    ||ERROR_DETAILS||\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    </div>\r\n    <br />\r\n    <div>\r\n        Thank you,\r\n    </div>\r\n    <br />\r\n    <br />\r\n    <div>\r\n        Note: This is an automatic message generated by ESKADENIA system.\r\n    </div>\r\n</body>\r\n</html>";

		private ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2007_SP1);

		private readonly ILogger<EmailConfiguration> _Logger;

		public EwsService(ILogger<EmailConfiguration> _logger)
		{
			_Logger = _logger;
			_emailConfiguration = SharedSettings.EmailConfiguration;
		}

		private static bool RedirectionUrlValidationCallback(string redirectionUrl)
		{
			bool result = false;
			Uri redirectionUri = new Uri(redirectionUrl);
			if (redirectionUri.Scheme == "https")
			{
				result = true;
			}
			return result;
		}

		public async Task<bool> SendAsync(string MassageBody, CancellationToken ct = default(CancellationToken))
		{
			try
			{
				MimeMessage mail = new MimeMessage
				{
					From = { (InternetAddress)new MailboxAddress(_emailConfiguration.DisplayName, _emailConfiguration.From ?? _emailConfiguration.From) },
					Sender = new MailboxAddress(_emailConfiguration.DisplayName ?? _emailConfiguration.DisplayName, _emailConfiguration.From ?? _emailConfiguration.From)
				};
				foreach (string mailAddress in SharedSettings.Emails)
				{
					mail.To.Add(MailboxAddress.Parse(mailAddress));
				}
				BodyBuilder body = new BodyBuilder();
				mail.Subject = _emailConfiguration.Subject;
				body.HtmlBody = MassageBody;
				mail.Body = body.ToMessageBody();
				using SmtpClient smtp = new SmtpClient();
				if (_emailConfiguration.UseSSL)
				{
					await smtp.ConnectAsync(_emailConfiguration.SmtpServer, _emailConfiguration.Port, SecureSocketOptions.SslOnConnect, ct);
				}
				else if (_emailConfiguration.UseStartTls)
				{
					await smtp.ConnectAsync(_emailConfiguration.SmtpServer, _emailConfiguration.Port, SecureSocketOptions.StartTls, ct);
				}
				else
				{
					smtp.ServerCertificateValidationCallback = (object s, X509Certificate? c, X509Chain? h, SslPolicyErrors e) => true;
					smtp.Connect(_emailConfiguration.SmtpServer, _emailConfiguration.Port, useSsl: false);
				}
				await smtp.SendAsync(mail, ct);
				await smtp.DisconnectAsync(quit: true, ct);
				return true;
			}
			catch (Exception ex)
			{
				Exception e2 = ex;
				_Logger.LogInformation(e2.Message);
				return false;
			}
		}

		private void Build()
		{
			try
			{
				service.Credentials = new WebCredentials(_emailConfiguration.UserName, _emailConfiguration.Password);
				service.UseDefaultCredentials = true;
				service.TraceEnabled = true;
				service.TraceFlags = TraceFlags.All;
				service.Credentials = new WebCredentials(_emailConfiguration.UserName, _emailConfiguration.Password, _emailConfiguration.SmtpServer);
				service.AutodiscoverUrl(_emailConfiguration.UserName, RedirectionUrlValidationCallback);
			}
			catch (Exception ex)
			{
				string x = ex.Message;
				_Logger.LogInformation(ex.Message);
			}
		}

		public async void SendEmail(string Body)
		{
			_ = service.UserAgent;
			try
			{
				await SendAsync(new MessageBody(AddingBody(Body)));
			}
			catch (Exception ex)
			{
				Exception e = ex;
				_ = e.Message;
			}
		}

		public string AddingBody(string Body)
		{
			string MailText = Templete;
			return MailText.Replace("||ERROR_DETAILS||", Body);
		}
	}
}
