using System;

namespace SharedSetup.Domain.Common.CustomAttributes
{
	public class DBName : Attribute
	{
		public string Name { get; set; }

		public bool RequiredOnUpdate { get; set; }

		public bool RequiredOnAdd { get; set; }

		public bool AutoGenerated { get; set; }

		public DBName(string name, bool requiredOnAdd = true, bool requiredOnUpdate = true, bool autoGenerated = false)
		{
			Name = name;
			RequiredOnAdd = requiredOnAdd;
			RequiredOnUpdate = requiredOnUpdate;
			AutoGenerated = autoGenerated;
		}
	}
}
